insert into families (address, city, state, zip) values ('11355 NW Reeves St.', 'Portland', 'OR', '97229');
\copy families (address, city, state, zip) from 'families.csv' csv header quote as '"';


create table churches (id integer generated by default as identity primary key, name text, address text, city text, state text, zip text, current boolean not null default false, size float, price decimal, notes text);
\copy churches (name, address, city, state, zip, size, price, notes) from 'churches.csv' csv header quote '"';

alter table families add column latitude float;
alter table families add column longitude float;
alter table churches add column latitude float;
alter table churches add column longitude float;

CREATE TABLE trips (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id   INTEGER NOT NULL REFERENCES families (id) ON DELETE CASCADE,
  church_id   INTEGER NOT NULL REFERENCES churches (id) ON DELETE CASCADE,
  day_of_week TEXT NOT NULL,
  time_of_day TIME NOT NULL,
  minutes     FLOAT NOT NULL
);

alter table families add column place_id text;
alter table churches add column place_id text;

