insert into families (address, city, state, zip) values ('11355 NW Reeves St.', 'Portland', 'OR', '97229');
\copy families (address, city, state, zip) from 'families.csv' csv header quote as '"';


create table churches (id integer generated by default as identity primary key, name text, address text, city text, state text, zip text, current boolean not null default false, size float, price decimal, notes text);
\copy churches (name, address, city, state, zip, size, price, notes) from 'churches.csv' csv header quote '"';

alter table families add column latitude float;
alter table families add column longitude float;
alter table churches add column latitude float;
alter table churches add column longitude float;

CREATE TABLE trips (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id    INTEGER NOT NULL REFERENCES families (id) ON DELETE CASCADE,
  church_id    INTEGER NOT NULL REFERENCES churches (id) ON DELETE CASCADE,
  arrival_time TIMESTAMP WITH TIME ZONE NOT NULL,
  seconds      FLOAT NOT NULL
);
create unique index idx_trips_family_church_arrival_time on trips (family_id, church_id, arrival_time);

alter table families add column place_id text;
alter table churches add column place_id text;

create unique index idx_churches_address on churches (coalesce(name, ''), address);

-- add more churches
create temporary table churches_input (like churches including all);
\copy churches_input (name, address, city, state, zip, size, price, notes) from 'churches.csv' csv header quote '"';
insert into churches (name, address, city, state, zip, size, price, notes) select name, address, city, state, zip, size, price, notes from churches_input on conflict (coalesce(name, ''), address) do nothing;
